### ISSUE TITLE
orderitem表结构需要重新更新下

### ISSUE THREAD

**Issue by liankui** [zhoushuguang/lebron#34]
https://github.com/zhoushuguang/lebron/blob/faf0719a58af6667ac1d413cb2096b69b768a1c6/sql/mall.sql#L107
1.字段按照其他表统一为没有下划线格式
2.id增加AUTO_INCREMENT属性

CREATE TABLE `orderitem`
(
    `id`               bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '订单子表id',
    `orderid`          varchar(64)         NOT NULL DEFAULT '' COMMENT '订单id',
    `userid`           bigint(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
    `proid`            bigint(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '商品id',
    `proname`          varchar(100)        NOT NULL DEFAULT '' COMMENT '商品名称',
    `proimage`         varchar(500)        NOT NULL DEFAULT '' COMMENT '商品图片地址',
    `currentunitprice` decimal(20, 2)      NOT NULL DEFAULT 0 COMMENT '生成订单时的商品单价，单位是元,保留两位小数',
    `quantity`         int(10)             NOT NULL DEFAULT 0 COMMENT '商品数量',
    `totalprice`       decimal(20, 2)      NOT NULL DEFAULT 0 COMMENT '商品总价,单位是元,保留两位小数',
    `create_time`      timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`      timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `ix_orderid` (`orderid`),
    KEY `ix_userid` (`userid`),
    KEY `ix_proid` (`proid`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='订单明细表';

**Comment by kehuai007** [comment]
你好，
     邮件已送到
