### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by hkb1990** [zhoushuguang/lebron#44]
https://github.com/zhoushuguang/lebron/blob/ffeeb9fd62bb66c4851906739a08debbfb94df3e/apps/seckill/rmq/internal/service/service.go#L107

https://github.com/zhoushuguang/lebron/blob/ffeeb9fd62bb66c4851906739a08debbfb94df3e/apps/seckill/rmq/internal/service/service.go#L117

为什么这两个地方要对err做判断而不是e？

**Comment by kehuai007** [comment]
你好，
     邮件已送到

**Comment by kehuai007** [comment]
你好，
     邮件已送到
