### ISSUE TITLE
为什么添加rpc会报如下的错误？

### ISSUE THREAD

**Issue by krisice** [zhoushuguang/lebron#46]
cannot use zrpc.MustNewClient(c.GraphRPC) (value of type \"github.com/zeromicro/go-zero/zrpc/internal\".Client) as grpc.ClientConnInterface value in argument to graph.NewGraphClient: \"github.com/zeromicro/go-zero/zrpc/internal\".Client does not implement grpc.ClientConnInterface (missing method Invoke)",

**Comment by kehuai007** [comment]
你好，
     邮件已送到

**Comment by krisice** [comment]
没问题啦，搞定啦。
