### ISSUE TITLE
mapreduce error

### ISSUE THREAD

**Issue by PittYao** [zhoushuguang/lebron#8]
1. Request Product-Rpc  method products  mapreduce error
![image](https://user-images.githubusercontent.com/26101917/173354776-11d63949-789f-413f-9f94-2c34bafd51fc.png)

2.Fix: pid is string not int64
![image](https://user-images.githubusercontent.com/26101917/173355000-129676ef-58d5-4c99-8261-ccd17874a93b.png)
like this:
![image](https://user-images.githubusercontent.com/26101917/173355041-2c819aa1-a680-49b2-8795-a2b1b4a9e171.png)

**Comment by zhoushuguang** [comment]
非常感谢，已经修复了
